[custom]
;谷歌FCM是推送服务,谷歌服务->谷歌服务
ruleset=🎯 全球直连,[]GEOSITE,private
ruleset=🎯 全球直连,[]GEOIP,private,no-resolve
; 个人规则集（GitHub Raw）
ruleset=REJECT,clash-classic:https://raw.githubusercontent.com/ytq77/Network-HomeLab/refs/heads/main/OpenClash/yx_rules/yx_reject.yaml,28800
ruleset=🎯 全球直连,clash-classic:https://raw.githubusercontent.com/ytq77/Network-HomeLab/refs/heads/main/OpenClash/yx_rules/yx_direct.yaml,28800
ruleset=🌍 强制代理,clash-classic:https://raw.githubusercontent.com/ytq77/Network-HomeLab/refs/heads/main/OpenClash/yx_rules/yx_proxy.yaml,28800

; 自定义直连
ruleset=🎯 全球直连,clash-domain:https://api.asailor.org/Custom_OpenClash_Rules/main/rule/Custom_Direct_Domain.yaml,28800
ruleset=🎯 全球直连,clash-classic:https://api.asailor.org/Custom_OpenClash_Rules/main/rule/Custom_Direct_Classical_IP.yaml,28800

; 自定义强制代理
ruleset=🌍 强制代理,clash-domain:https://api.asailor.org/Custom_OpenClash_Rules/main/rule/Custom_Proxy_Domain.yaml,28800
ruleset=🌍 强制代理,clash-classic:https://api.asailor.org/Custom_OpenClash_Rules/main/rule/Custom_Proxy_Classical_IP.yaml,28800

ruleset=🎯 全球直连,[]GEOSITE,google-cn
ruleset=🎯 全球直连,[]GEOSITE,category-games@cn

ruleset=🎯 全球直连,clash-classic:https://api.asailor.org/Custom_OpenClash_Rules/main/rule/Steam_CDN_Classical.yaml,28800
ruleset=🎯 全球直连,[]GEOSITE,category-game-platforms-download

ruleset=🎯 全球直连,[]GEOSITE,category-public-tracker

ruleset=🌍 强制代理,[]GEOSITE,openai
ruleset=🌍 强制代理,[]GEOSITE,bing
ruleset=🌍 强制代理,[]GEOSITE,category-ai-!cn
ruleset=🌍 强制代理,[]GEOSITE,github
ruleset=🌍 强制代理,[]GEOSITE,category-communication
ruleset=🌍 强制代理,[]GEOSITE,category-social-media-!cn
ruleset=🌍 强制代理,[]GEOIP,telegram,no-resolve
ruleset=🌍 强制代理,[]GEOIP,twitter,no-resolve
ruleset=🌍 强制代理,[]GEOIP,facebook,no-resolve
ruleset=🌍 强制代理,[]GEOSITE,tiktok
ruleset=🌍 强制代理,[]GEOSITE,youtube
ruleset=🌍 强制代理,[]GEOSITE,netflix
ruleset=🌍 强制代理,[]GEOSITE,disney
ruleset=🌍 强制代理,[]GEOIP,netflix,no-resolve
ruleset=🌍 强制代理,[]GEOSITE,hbo
ruleset=🌍 强制代理,[]GEOSITE,apple-tvplus
ruleset=🌍 强制代理,[]GEOSITE,primevideo
ruleset=🌍 强制代理,[]GEOSITE,category-emby
ruleset=🌍 强制代理,[]GEOSITE,spotify
ruleset=🌍 强制代理,[]GEOSITE,bahamut
; AppleTV 必须在 Apple 之前
ruleset=🍎 苹果服务,[]GEOSITE,apple
; OneDrive 在 Microsoft 之前
ruleset=Ⓜ️ 微软服务,[]GEOSITE,onedrive
ruleset=Ⓜ️ 微软服务,[]GEOSITE,microsoft
; FCM 在 Google 之前
ruleset=🔔 谷歌FCM,[]GEOSITE,googlefcm
ruleset=🌍 强制代理,[]GEOSITE,google
ruleset=🌍 强制代理,[]GEOIP,google,no-resolve
ruleset=🌍 强制代理,[]GEOSITE,paypal
ruleset=🌍 强制代理,[]GEOSITE,category-ecommerce
ruleset=🍄 任任索索,[]GEOSITE,playstation
ruleset=🍄 任任索索,[]GEOSITE,nintendo
ruleset=🚂 Steam,[]GEOSITE,steam
ruleset=🎮 游戏平台,[]GEOSITE,category-games
ruleset=🌍 强制代理,[]GEOSITE,category-entertainment
ruleset=⏱️ 测速工具,[]GEOSITE,category-speedtest
ruleset=🌍 强制代理,[]GEOSITE,gfw
; 国内域名/IP 兜底直连
ruleset=🎯 全球直连,[]GEOSITE,cn
ruleset=🎯 全球直连,[]GEOIP,cn,no-resolve

; 非标端口优化
ruleset=🔀 非标端口,clash-classic:https://api.asailor.org/Custom_OpenClash_Rules/main/rule/Custom_Port_Direct.yaml,28800

; 漏网之鱼
ruleset=🐟 漏网之鱼,[]FINAL


custom_proxy_group=🌍 强制代理`select`[]🎪 自建节点`[]🎯 全球直连
custom_proxy_group=🔔 谷歌FCM`select`[]🎯 全球直连`[]🎪 自建节点
custom_proxy_group=🍎 苹果服务`select`[]🎯 全球直连`[]🎪 自建节点
custom_proxy_group=Ⓜ️ 微软服务`select`[]🎯 全球直连`[]🎪 自建节点
custom_proxy_group=🛸 主机锚定`select`[]👨‍🦽 手动节点`[]🎯 全球直连
custom_proxy_group=🍄 任任索索`select`[]🎪 自建节点`[]🎯 全球直连
custom_proxy_group=🚂 Steam`select`[]🎪 自建节点`[]🎯 全球直连
custom_proxy_group=🎮 游戏平台`select`[]🎯 全球直连`[]🎪 自建节点
custom_proxy_group=⏱️ 测速工具`select`[]🎯 全球直连`[]🎪 自建节点
custom_proxy_group=🔀 非标端口`select`[]🐟 漏网之鱼`[]🎯 全球直连
custom_proxy_group=🐟 漏网之鱼`select`[]🎪 自建节点`[]🎯 全球直连

# === [地区测试组] ===
custom_proxy_group=🎪 自建节点`select`.*
custom_proxy_group=👨‍🦽 手动节点`select`.*

custom_proxy_group=🎯 全球直连`select`[]DIRECT

;下方参数请勿修改
enable_rule_generator=true
overwrite_original_rules=true